apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
  namespace: likes-web-app
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      nodeSelector:
        node_type: workload
      containers:
      - name: redis-server
        image: redis:7.0.10
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: redis-server
  namespace: likes-web-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-server